version: '3.8'

services:
  # MQTTブローカー (既存)
  mosquitto:
    build:
      context: ./mosquitto
    container_name: cocoba-local-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    restart: always

  # S3/DynamoDBのエミュレータ (追加)
  localstack:
    container_name: cocoba-localstack
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack の統合エンドポイント
      - "127.0.0.1:4510-4559:4510-4559"  # 外部サービス用ポート
    environment:
      - SERVICES=s3,dynamodb            # 使うサービスを指定
      - DEBUG=1
    volumes:
      - "./localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  mosquitto_data:
  mosquitto_log:
